### ISSUE TITLE
Request for Soldering schematics / wiring diagram

### ISSUE THREAD

**Issue by tolkiman** [smoca-ag/m5stack_co2_sensor#1]
Step 4 simply states "Connect the SCD30 module to the proto module. We used headers."

I would really like to build this project, however its hard to make out which connections to solder and what to connect exactly. Would you be able to supply a simple wiring diagram / soldering schematics? Thanks!

**Comment by 4nd2in** [comment]
On page of the [datasheet](https://cdn.sparkfun.com/assets/1/a/7/9/9/Sensirion_CO2_Sensors_SCD30_Preliminary-Datasheet.pdf) 6 you can see the pin-out diagram of the scd30. You need to connect VDD with 3V3, GND with GND, TX/SCL with pin 5 and RX/SDA with pin 2. The other pins don't need to be connected to the proto module.

**Comment by tolkiman** [comment]
Fantastic, thanks for the support!
