### ISSUE TITLE
Too heavy SW

### ISSUE THREAD

**Issue by Kabron287** [smoca-ag/m5stack_co2_sensor#2]
Your project does not work. How to threw out WiFiManager, MQTT, WEB and all this trash and leave only essential.

> M5Core2 initializing...axp: vbus limit off
axp: gpio1 init
axp: gpio2 init
axp: rtc battery charging enabled
axp: esp32 power voltage was set to 3.35v
axp: lcd backlight voltage was set to 2.80v
axp: lcd logic and sdcard voltage preset to 3.3v
axp: vibrator voltage preset to 2v
touch: FT6336 ready (fw id 0x10 rel 1, lib 0x300E)
OK
Loaded state file.
deserializeJson() failed: InvalidInput
cgw4Q9da
Setting time: Fri Jun 30 20:49:34 2000
The current date/time in Zuerich is: Fri Jun 30 22:49:34 2000Initializing SD card...
File already exists
WiFi off status: 6
Failed to obtain time
we are to slow:5019
Message appended
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.

**Comment by Kabron287** [comment]
Problem was in my sensor driver.
I use  T6703.

**Comment by pfy** [comment]
Hi

The NTP Code has a bug as well. If the device does not have the correct time, it might busy loop the ntp code. The we are to slow:5019 message confirms this -> we will push an update next week.


isn't the T6703 more expensive than the sensirion part ? The sensirion costs about 50 CHF and the T6703 about 100 CHF ?


best regards

David Gunzinger
CTO, Co-Founder

Smoca AG ǀ Technoparkstrasse 2 ǀ 8406 Winterthur
G: +41 52 508 59 57
M: ***@***.***
W: www.smoca.ch

**Comment by Kabron287** [comment]
Thanks for answer/
About 25 CHF on aliexpress.
