### ISSUE TITLE
Parts ordering via bastelgarage.ch

### ISSUE THREAD

**Issue by tobru** [smoca-ag/m5stack_co2_sensor#5]
This issue is a FYI issue, can be closed any time: The parts needed for this project are available at bastelgarage.ch, which is easy for Swiss people. Maybe you want to link to it from the README. Disclaimer: I'm not affiliated with bastelgarage.ch, just a fan of them (and this project).

**Comment by AlfMueller** [comment]
This issue is a FYI issue, can be closed any time: 
add Link for 3d Print Backcover sourcefile on thingiverse:
https://www.thingiverse.com/thing:4651700

**Comment by marcelstoer** [comment]
This is actually OT but @AlfMueller did you find the case on Thingiverse more useful then the one in this repository at https://github.com/smoca-ag/m5stack_co2_sensor/blob/main/case/encasing3.stl?
